name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Autenticarse en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Docker para Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Construir y subir imagen Docker a Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/cicdlab-449501/ci-cd-ia/ci-cd-ia:latest .
          docker push us-central1-docker.pkg.dev/cicdlab-449501/ci-cd-ia/ci-cd-ia:latest

      - name: Desplegar en Cloud Run
        run: |
          gcloud run deploy ci-cd-ia \
            --image us-central1-docker.pkg.dev/cicdlab-449501/ci-cd-ia/ci-cd-ia:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
